// Code generated by entc, DO NOT EDIT.

package validator

const (
	// Label holds the string label denoting the validator type in the database.
	Label = "validator"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldAccountID holds the string denoting the account_id field in the database.
	FieldAccountID = "account_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldCommission holds the string denoting the commission field in the database.
	FieldCommission = "commission"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldBalance holds the string denoting the balance field in the database.
	FieldBalance = "balance"
	// FieldReserved holds the string denoting the reserved field in the database.
	FieldReserved = "reserved"
	// FieldLocked holds the string denoting the locked field in the database.
	FieldLocked = "locked"
	// FieldOwnStake holds the string denoting the own_stake field in the database.
	FieldOwnStake = "own_stake"
	// FieldTotalStake holds the string denoting the total_stake field in the database.
	FieldTotalStake = "total_stake"
	// FieldIdentity holds the string denoting the identity field in the database.
	FieldIdentity = "identity"
	// FieldNominators holds the string denoting the nominators field in the database.
	FieldNominators = "nominators"
	// FieldParent holds the string denoting the parent field in the database.
	FieldParent = "parent"
	// FieldChildren holds the string denoting the children field in the database.
	FieldChildren = "children"
	// FieldHash holds the string denoting the hash field in the database.
	FieldHash = "hash"
	// FieldChain holds the string denoting the chain field in the database.
	FieldChain = "chain"
	// Table holds the table name of the validator in the database.
	Table = "validators"
)

// Columns holds all SQL columns for validator fields.
var Columns = []string{
	FieldID,
	FieldAccountID,
	FieldName,
	FieldCommission,
	FieldStatus,
	FieldBalance,
	FieldReserved,
	FieldLocked,
	FieldOwnStake,
	FieldTotalStake,
	FieldIdentity,
	FieldNominators,
	FieldParent,
	FieldChildren,
	FieldHash,
	FieldChain,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}
