// Code generated by entc, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// BlocksColumns holds the columns for the "blocks" table.
	BlocksColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "number", Type: field.TypeUint32},
		{Name: "author_id", Type: field.TypeString},
		{Name: "finalized", Type: field.TypeBool},
		{Name: "extrinsics_count", Type: field.TypeInt},
		{Name: "extrinsics", Type: field.TypeJSON, Nullable: true},
		{Name: "chain", Type: field.TypeString},
	}
	// BlocksTable holds the schema information for the "blocks" table.
	BlocksTable = &schema.Table{
		Name:       "blocks",
		Columns:    BlocksColumns,
		PrimaryKey: []*schema.Column{BlocksColumns[0]},
	}
	// ValidatorsColumns holds the columns for the "validators" table.
	ValidatorsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeInt, Increment: true},
		{Name: "account_id", Type: field.TypeString},
		{Name: "name", Type: field.TypeString},
		{Name: "commission", Type: field.TypeFloat64},
		{Name: "status", Type: field.TypeString},
		{Name: "balance", Type: field.TypeString},
		{Name: "reserved", Type: field.TypeString},
		{Name: "locked", Type: field.TypeJSON},
		{Name: "own_stake", Type: field.TypeString},
		{Name: "total_stake", Type: field.TypeString},
		{Name: "identity", Type: field.TypeJSON},
		{Name: "nominators", Type: field.TypeJSON},
		{Name: "parent", Type: field.TypeJSON},
		{Name: "children", Type: field.TypeJSON},
		{Name: "hash", Type: field.TypeString},
		{Name: "chain", Type: field.TypeString},
	}
	// ValidatorsTable holds the schema information for the "validators" table.
	ValidatorsTable = &schema.Table{
		Name:       "validators",
		Columns:    ValidatorsColumns,
		PrimaryKey: []*schema.Column{ValidatorsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		BlocksTable,
		ValidatorsTable,
	}
)

func init() {
}
