// Code generated by entc, DO NOT EDIT.

package block

const (
	// Label holds the string label denoting the block type in the database.
	Label = "block"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldNumber holds the string denoting the number field in the database.
	FieldNumber = "number"
	// FieldAuthorID holds the string denoting the author_id field in the database.
	FieldAuthorID = "author_id"
	// FieldFinalized holds the string denoting the finalized field in the database.
	FieldFinalized = "finalized"
	// FieldExtrinsicsCount holds the string denoting the extrinsics_count field in the database.
	FieldExtrinsicsCount = "extrinsics_count"
	// FieldExtrinsics holds the string denoting the extrinsics field in the database.
	FieldExtrinsics = "extrinsics"
	// FieldChain holds the string denoting the chain field in the database.
	FieldChain = "chain"
	// Table holds the table name of the block in the database.
	Table = "blocks"
)

// Columns holds all SQL columns for block fields.
var Columns = []string{
	FieldID,
	FieldNumber,
	FieldAuthorID,
	FieldFinalized,
	FieldExtrinsicsCount,
	FieldExtrinsics,
	FieldChain,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NumberValidator is a validator for the "number" field. It is called by the builders before save.
	NumberValidator func(uint32) error
)
